### PR TITLE
Skip adding separator if ele value is empty

### PR DESCRIPTION
**Pull request by AkhileshChaikam**

### CODE REVIEW

**Comment by AkhileshChaikam** [comment]
@ReturnZero23  @aperezdc Could you please review this PR

**Comment by AkhileshChaikam** [comment]
@ReturnZero23 Reminder!!

**Comment by aperezdc** [comment]
To be honest, I am not really well acquainted with the source code, and I don't feel comfortable doing a code review at this point, so I will defer to @ReturnZero23 

At any rate, do you have an example which hits the bug that this patch is trying to solve? It would be good to add it as a test case.

**Comment by returnzero23** [comment]
@AkhileshChaikam I agree with @aperezdc . do you have an example which hits the bug. I want to add it to test case.

**Pull request merged**
